### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by JottaUp** [avenger11/HomeOS#1]
Hello

First of all, this lovelace method is spectacular and I'm trying to do something like that, if that's okay.

But I have a small problem that when loading the view, Hassio gives an error where it cannot find a grid-layout configuration.

can you help me?

![image](https://github.com/avenger11/HomeOS/assets/91528554/049818a3-c5aa-4229-833d-58b6b732d91f)

**Comment by avenger11** [comment]
Hi Jotta,

I do have the same bug, it appears with a recent update of grid-layout. 
Simple not permanent fix : the top bar appear click on reload the resources in the 3 dots. it should clear it.
I thinks it's maybe related to the order of how HA load resource because it does not always appear ( at least on my set-up)

hope this help
